# When changing the keys here, run the following command to update the SOPS files:
#   for secret_file in secrets/*.yaml;
#     sops updatekeys "$secret_file"
#   end
#
# Age keys are obtained from SSH keys by running
#   nix run nixpkgs#ssh-to-age -- -i <pub_key>
# or
#   nix run nixpkgs#ssh-to-age -- -i <(echo "ssh-ed25519 ...")
keys:
  # users
  - &ramses age1wm7aec0vd5trqqvk6n97kh8r3x0jpue9gne9enr92kdjk63f5e8s9gjy0x
  # servers
  - &starbook age17q0t4n47nswcsnxz5n5kuzd544af7ev3rhvhwrawl5suvv67jpjs7r485e
  - &nuke     age1ztmgmhauuaxca9vjl4csr80lt26m47tqh8nk252vytxjtc3pze5s6s56m5
creation_rules:
  - path_regex: 'secrets/github-secrets\.yaml$'
    key_groups:
    - age:
      - *ramses
      - *starbook
      - *nuke
  - path_regex: 'secrets/ramses-secrets\.yaml$'
    key_groups:
    - age:
      - *ramses
      - *starbook
      - *nuke
