# When changing the keys here, run the following command to update the SOPS files:
#   for secret_file in secrets/*.yaml; do
#     sops updatekeys "${secret_file}
#   done
keys:
  # users
  - &ramses age1wkxv0fjg5k0u2fg48s2cna03vwhtwthmart2d2d72eg8hm5hdansk8rc9u
  - &ramses2 age1wm7aec0vd5trqqvk6n97kh8r3x0jpue9gne9enr92kdjk63f5e8s9gjy0x
  # servers
  - &starbook age1lkddy5f6duxxgdf92eng0x8juqm492klzu4ffcyrsh6y8ywlzcnsw8a6j4
  - &nixer    age1e4larxc5ydy4kar30ar2x4uzg4u2lchjhcefnzvxmx7a9rs3hygswqrmez
creation_rules:
  - path_regex: 'secrets/github-secrets\.yaml$'
    key_groups:
    - age:
      - *ramses
      - *ramses2
      - *starbook
      - *nixer
  - path_regex: 'secrets/ramses-secrets\.yaml$'
    key_groups:
    - age:
      - *ramses
      - *ramses2
      - *starbook
      - *nixer
  - path_regex: 'secrets/starbook-secrets\.yaml$'
    key_groups:
    - age:
      - *ramses
      - *ramses2
      - *starbook
  - path_regex: 'secrets/nixer-secrets\.yaml$'
    key_groups:
    - age:
      - *ramses
      - *ramses2
      - *nixer

