# When changing the keys here, run the following command to update SOPS files:
#   sops updatekeys secrets/*.yaml
keys:
  # users
  - &ramses age1wkxv0fjg5k0u2fg48s2cna03vwhtwthmart2d2d72eg8hm5hdansk8rc9u
  # servers
  - &starbook age1lkddy5f6duxxgdf92eng0x8juqm492klzu4ffcyrsh6y8ywlzcnsw8a6j4
  - &nixer    age1e4larxc5ydy4kar30ar2x4uzg4u2lchjhcefnzvxmx7a9rs3hygswqrmez
creation_rules:
  - path_regex: 'secrets/sops/github-secrets\.yaml$'
    key_groups:
    - age:
      - *ramses
      - *starbook
      - *nixer
  - path_regex: 'secrets/sops/ramses-secrets\.yaml$'
    key_groups:
    - age:
      - *ramses
      - *starbook
      - *nixer
  - path_regex: 'secrets/sops/starbook-secrets\.yaml$'
    key_groups:
    - age:
      - *ramses
      - *starbook
  - path_regex: 'secrets/sops/nixer-secrets\.yaml$'
    key_groups:
    - age:
      - *ramses
      - *nixer

